apiVersion: batch/v1
kind: Job
metadata:
  namespace: test
  name: test
spec:
  backoffLimit: 25
  template:
    spec:
      - name: cosign
        image: cgr.dev/chainguard/cosign:latest@sha256:76ee285468020e657481f22df393c5b133df19a807483373739a9d317a4d75a8
